const $ = s => document.querySelector(s); let targets = [], editing = null;
const api = async (url, options = {}) => { const response = await fetch(url, {headers:{"Content-Type":"application/json"}, ...options}); if (!response.ok) throw new Error((await response.json().catch(()=>({}))).detail || "Something went wrong"); return response.status === 204 ? null : response.json(); };
const toast = message => { $("#toast").textContent = message; $("#toast").classList.add("show"); setTimeout(() => $("#toast").classList.remove("show"), 3500); };
const formatDate = value => value ? new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "Not yet";
function showPage(name) { document.querySelectorAll(".page,.nav-link").forEach(e=>e.classList.remove("active")); $(`#${name}`).classList.add("active"); $(`[data-page="${name}"]`).classList.add("active"); $("#page-title").textContent = name === "library" ? "Your research library." : name === "targets" ? "Define your listening posts." : "Research, without the noise."; if(name === "library") loadPosts(); }
function postHTML(post) { return `<article class="post"><div class="post-meta"><span>r/${esc(post.subreddit)}</span><span>•</span><span>${formatDate(post.created_utc)}</span><span class="score">↑ ${post.score}</span></div><a href="${esc(post.url)}" target="_blank" rel="noreferrer">${esc(post.title)}</a><p>${esc(post.body || "").slice(0,280)}</p><footer><span>${esc(post.target_name)}</span><span>${post.num_comments} comments · u/${esc(post.author)}</span>${post.matched_keywords ? `<span class="matched">${esc(post.matched_keywords)}</span>` : ""}</footer></article>`; }
function esc(value="") { const d=document.createElement("div"); d.textContent=value; return d.innerHTML; }
async function loadOverview(){ const data=await api("/api/overview"); $("#post-total").textContent=data.posts; $("#all-targets").textContent=data.targets; $("#active-targets").textContent=data.active_targets; $("#last-fetch").textContent=formatDate(data.last_fetch); const posts=await api("/api/posts"); $("#recent-posts").innerHTML=posts.slice(0,5).map(postHTML).join("") || `<div class="empty"><b>Your library is empty.</b><span>Create a target, then fetch it to collect matching Reddit posts.</span></div>`; }
function targetHTML(t){return `<article class="target-card ${t.paused?"paused":""}"><div class="target-top"><span class="platform reddit">r/</span><span class="state">${t.paused?"Paused":"Active"}</span></div><h3>${esc(t.name)}</h3><p class="subreddits">${t.subreddit_list.map(esc).join(" · ")}</p><p class="keywords">${t.include_keywords ? `Includes: ${esc(t.include_keywords)}` : "No include keywords"}${t.exclude_keywords ? `<br>Excludes: ${esc(t.exclude_keywords)}` : ""}</p><footer><span>${esc(t.sort)} · ${esc(t.time_filter)}</span><div><button data-action="fetch" data-id="${t.id}">Fetch</button><button data-action="edit" data-id="${t.id}">Edit</button><button data-action="delete" data-id="${t.id}" class="danger">Delete</button></div></footer></article>`}
async function loadTargets(){ targets=await api("/api/targets"); $("#targets-grid").innerHTML=targets.map(targetHTML).join(""); $("#empty-targets").hidden=targets.length>0; $("#target-count").textContent=targets.length; $("#filter-target").innerHTML=`<option value="">All targets</option>`+targets.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(""); }
function openTarget(target){ editing=target||null; $("#target-form").reset(); $("#form-error").textContent=""; $("#dialog-title").textContent=target?"Edit target":"Create a target"; $("#target-id").value=target?.id||""; ["name","platform","subreddits","sort"].forEach(k=>$("#"+k).value=target?.[k]||$("#"+k).value); $("#include-keywords").value=target?.include_keywords||""; $("#exclude-keywords").value=target?.exclude_keywords||""; $("#time-filter").value=target?.time_filter||"week"; $("#paused").checked=target?.paused||false; $("#target-dialog").showModal(); }
async function loadPosts(){ const q=new URLSearchParams(); if($("#filter-target").value)q.set("target_id",$("#filter-target").value); if($("#filter-keyword").value)q.set("keyword",$("#filter-keyword").value); if($("#filter-date").value)q.set("after",$("#filter-date").value); if($("#filter-score").value)q.set("min_score",$("#filter-score").value); const posts=await api("/api/posts?"+q); $("#result-count").textContent=`${posts.length} post${posts.length===1?"":"s"}`; $("#library-posts").innerHTML=posts.map(postHTML).join("")||`<div class="empty"><b>No matching posts.</b><span>Adjust your filters or fetch an active target.</span></div>`; }
async function refresh(){ try{await Promise.all([loadTargets(),loadOverview()]);}catch(e){toast(e.message)} }
document.addEventListener("click", async e=>{ const go=e.target.closest("[data-page],[data-goto]"); if(go)showPage(go.dataset.page||go.dataset.goto); if(e.target.matches("#new-target,#new-target-2"))openTarget(); const action=e.target.dataset.action,id=Number(e.target.dataset.id); if(action){ const t=targets.find(x=>x.id===id); if(action==="edit")openTarget(t); if(action==="delete"&&confirm(`Delete “${t.name}” and its saved posts?`)){await api(`/api/targets/${id}`,{method:"DELETE"});toast("Target deleted");refresh();} if(action==="fetch"){try{const r=await api(`/api/targets/${id}/fetch`,{method:"POST"});toast(`Saved ${r.inserted} new post(s)`);refresh();}catch(err){toast(err.message)}} }});
$("#target-form").addEventListener("submit",async e=>{e.preventDefault(); const data={name:$("#name").value,platform:"reddit",subreddits:$("#subreddits").value,include_keywords:$("#include-keywords").value,exclude_keywords:$("#exclude-keywords").value,sort:$("#sort").value,time_filter:$("#time-filter").value,paused:$("#paused").checked}; try{await api(editing?`/api/targets/${editing.id}`:"/api/targets",{method:editing?"PUT":"POST",body:JSON.stringify(data)}); $("#target-dialog").close();toast(editing?"Target updated":"Target created");refresh();}catch(err){$("#form-error").textContent=err.message}});
$("#close-dialog").onclick=$("#cancel-dialog").onclick=()=>$("#target-dialog").close(); $("#fetch-all").onclick=async()=>{try{const r=await api("/api/fetch",{method:"POST"});toast(`Checked ${r.targets_checked} target(s); saved ${r.inserted} new post(s)`);refresh()}catch(e){toast(e.message)}}; $("#apply-filters").onclick=loadPosts; $("#export-csv").onclick=()=>{const q=new URLSearchParams(); [["target_id","#filter-target"],["keyword","#filter-keyword"],["after","#filter-date"],["min_score","#filter-score"]].forEach(([key,sel])=>$(sel).value&&q.set(key,$(sel).value)); location=`/api/posts/export?${q}`}; refresh();
